/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker.cliente.presentacion;

import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import javax.swing.JComponent;
import org.w3c.dom.events.MouseEvent;
import poker.cliente.negocio.PokerClient;
import poker.servidor.negocio.Mesa;

/**
 *
 * @author llanos
 */
public class mesajuego extends javax.swing.JPanel  {
        private Mesa mesa=null;
        private PokerClient cliente=null;
       // private ActionListener lst =null;
    /**
     * Creates new form mesajuego
     */
    public mesajuego(PokerClient cliente,ActionListener lst) {
        initComponents();
        this.cliente = cliente;
        //this.lst=lst;
        jButton1.addActionListener(lst);
        jButton1.setActionCommand("btnrojo");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        mesapoker = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setMaximumSize(new java.awt.Dimension(1100, 650));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setPreferredSize(new java.awt.Dimension(1100, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        mesapoker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poker/cliente/presentacion/mesa.png"))); // NOI18N
        add(mesapoker, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
/*
private void tamañoicon(JComponent componente,String dirimagen){
    
    ImageIcon imagen = new ImageIcon(dirimagen);
    Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(componente.getWidth(),componente.getHeight(), Image.SCALE_DEFAULT));
    componente.setIcon(icono);
            
}
        
  */      
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel mesapoker;
    // End of variables declaration//GEN-END:variables

    
}
