/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poker.cliente.presentacion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import poker.cliente.negocio.PokerClient;
/**
 *
 * @author LIMBERT
 */
public class Principal extends javax.swing.JFrame implements ActionListener{
    private PokerClient cliente = null;
    private Clientesymesas p =null;
    private mesajuego m = null;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        iniciador();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 608, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     cambiarpanel();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    private void iniciador(){
        String nickName = JOptionPane.showInputDialog("Ingrese un nickName : ", "pedro");
       
        if(nickName.length() > 0 ){
            cliente = new PokerClient(5555, "localhost");
            cliente.conectarServidor(nickName);
            cargarjug_mesa();
             
        } 
    }

    public  void cargarjug_mesa(){
            p= new Clientesymesas(cliente,this);
            cliente.addEventListener(p);
            p.setBounds(1, 50, this.getWidth() - 10, this.getHeight() - 10);
            p.setVisible(true);
            this.getContentPane().add(p);
            
            
             m = new mesajuego(cliente,this);
             m.setBounds(1, 50, this.getWidth() - 10, this.getHeight() - 10);
             m.setVisible(false);
             this.getContentPane().add(m);
           /*
            PanelPrincipal.removeAll();
            PanelPrincipal.add(p);
            PanelPrincipal.revalidate();implements ActionListener
            PanelPrincipal.repaint();*/
    } 
    public void cargarmesajuego(){
             m = new mesajuego(cliente,this);
             m.setBounds(1, 50, this.getWidth() - 10, this.getHeight() - 10);
             this.getContentPane().add(m);
           /* PanelPrincipal.removeAll();
            PanelPrincipal.add(m);
            PanelPrincipal.revalidate();
            PanelPrincipal.repaint();*/
    }
    public  void cambiarpanel(){
        p.setVisible(false);
        cargarmesajuego();
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
       if(e.getActionCommand().equals("btnverde")){
                System.out.println("me presionaron en el panel verde");
                p.setVisible(false);
                m.setVisible(true);
                System.out.println("pase el verde");
                
            }else{
                if(e.getActionCommand().equals("btnrojo")){
                    m.setVisible(false);
                    p.setVisible(true);

                }
            }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
