package pruebas;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import jsocket.client.OnConnectedEventClient;
import jsocket.client.OnConnectedListenerClient;
import poker.cliente.negocio.PokerClient;

/**
 * Interfaz Principal del juego
 * @author Alex Limbert Yalusqui <limbertyalusqui@gmail.com>
 */
public class frmGame extends javax.swing.JFrame implements ActionListener, OnConnectedListenerClient{
    
    private GameView viewGame = null;
    private InicioView viewIni = null;
    
    private PokerClient cliente = null;
    private String nickName = "Error de usuario";
    public frmGame() {
        initComponents();
        this.login();
    }
    /**
     * Inicializa la vista inicial que se mostraran cuando inicie session
     */
    private void visualizarVistaInicial(){    
        viewIni = new InicioView(cliente, this);
        this.setLayout(new BorderLayout());
        
        this.getContentPane().add(viewIni, BorderLayout.CENTER);
        
    }
    /**
     * Metodo que oculta o muestra la vista inicial
     * @param estado Si es true muestra la vista , false la oculta
     */
    private void setVisibleVistaInicial(boolean estado){
        this.viewIni.setVisible(estado);
    }
    /**
     * Metodo que vizualiza la vista de Game en el formulario
     */
    private void visualizarVistaGame(){
        try{            
            viewGame = new GameView(cliente, this);
            // ademas pasamos el escuchador
            cliente.addEventListenerPackages(viewGame);
            viewGame.setVisible(true);
            this.setLayout(new BorderLayout());
            this.getContentPane().add(viewGame, BorderLayout.CENTER);                    
        }catch(Exception e){
            System.out.println("[frmGame.visualizarVistaGame]" + e.getMessage());
        }
    }
    /**
     * Metodo que elimina la vista Game del formulario
     */
    private void removeVistaGame(){
        this.viewGame.setVisible(false);
        this.getContentPane().remove(viewGame);
        cliente.removeEventListenerPackages(cliente);
        this.viewGame = null;
    }
    /**
     * Metodo que para iniciar session
     */
    private void login(){
        try {
            nickName =  JOptionPane.showInputDialog("Ingrese un nickName : ", "pedro");
            
            if(nickName == null || (nickName != null && ("".equals(nickName)))){
                throw new Exception("No se ingreso nombre");
            }

            
            if(nickName.length() > 0 ){
                cliente = new PokerClient(5555, "localhost");
                this.visualizarVistaInicial();
                cliente.addEventListenerSocket(this);
                cliente.addEventListenerPackages(viewIni);
                cliente.conectarServidor(nickName);            
            }
        } catch (Exception e) {            
            System.out.println("[frmGame.login]" + e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error",JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGame().setVisible(true);
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        try{
            String action = e.getActionCommand();
            String btn[] = action.split("-");

            if(btn[0].equals("btnMesaActual")){
                // es el boton de ingresar a mesa                
                System.out.println("actionPerformed : " + btn[1]);
                int idMesa = Integer.valueOf(btn[1]);
                if(idMesa > 0){
                    cliente.ingresarMesa(idMesa);
                    this.visualizarVistaGame();
                    this.setVisibleVistaInicial(false);
                }else{
                    System.out.println("[frmGame.actionPerformed] No hay idMesa");
                }
            }else{
                // aqui debe de ir otro boton
            }
        }catch(Exception ex){
            System.out.println("[frmGame.actionPerformed]" + ex.getMessage());
        }
    }

    @Override
    public void onConnect(Object o, OnConnectedEventClient ocec) {
        System.out.println("un suario conextado!!");
        this.setTitle("Usuario : <" + this.nickName + "> Conectado al servidor ");
    }

    @Override
    public void onDisconnect(Object o, OnConnectedEventClient ocec) {
        System.out.println("no implement frmGame.onDisconnect");
    }

    @Override
    public void onRead(Object o, OnConnectedEventClient ocec) {
        System.out.println("no implement frmGame.onRead");
    }

    @Override
    public void onConnectRefused() {
        System.out.println("no implement frmGame.onConnectRefused");
    }

    @Override
    public void onConnectFinally() {
        System.out.println("no implement frmGame.onConnectFinally");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}